name: deprector

on:
  push:

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  
  cli:
    name: CLI (${{ matrix.client-package }}/${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
        client-package:
          - idaes
          - watertap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package (pip)
        run: |
          pip install --progress-bar off setuptools wheel .
          deprector --help
      - name: Install client package (${{ matrix.client-package }})
        run: |
          pip install --progress-bar off ${{ matrix.client-package }}
      - name: Run collect
        run: |
          deprector collect ${{ matrix.client-package }}
      - name: Run analyze
        run: |
          deprector analyze ${{ matrix.client-package }}
      - uses: actions/upload-artifact@v3
        with:
          name: deprector-${{ matrix.client-package }}-${{ matrix.python-version }}
          path: "*.json"
