name: deprector

on:
  push:

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  
  cli:
    name: CLI (${{ matrix.client-package }}/${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
        client-package:
          - idaes
          - watertap
        include:
          - client-package: idaes
            client-package-pip-target: idaes-pse @ https://github.com/IDAES/idaes-pse/archive/main.zip
            collect-flags: -- -m unit
            analyze-flags: --callsite-registry idaes
          - client-package: watertap
            client-package-pip-target: watertap[testing] @ https://github.com/watertap-org/watertap/archive/main.zip
            collect-flags: ""
            analyze-flags: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package (pip)
        run: |
          pip install --progress-bar off setuptools wheel .
          deprector --help
      - name: Install client package (${{ matrix.client-package-pip-target }})
        run: |
          pip install --progress-bar off "${{ matrix.client-package-pip-target }}"
      - name: Install IDAES extensions
        run: |
          idaes get-extensions --verbose --extra petsc
      - name: Run collect
        run: |
          deprector collect ${{ matrix.client-package }} ${{ matrix.collect-flags }}
      - name: Run analyze
        run: |
          deprector analyze ${{ matrix.client-package }} ${{ matrix.analyze-flags }}
      - uses: actions/upload-artifact@v3
        with:
          name: deprector-${{ matrix.client-package }}-${{ matrix.python-version }}
          path: "*.json"
